baseURL =  'https://nikosavg.github.io/'
languageCode =  'en-us'
title =  'Nikos Avgoustis'
theme =  'anubis'
enableRobotsTXT = "true"
paginate =  5


googleAnalytics = "G-JGMV3N6C4M"

[author]
name = "Nikos Avgoustis"

[params]
style = "light-without-switcher"
dateFormat = "02-01-2006"
mail = "nik.avg@hotmail.com"
author = "Nikos Avgoustis"
readNextPosts = 5  # show 5 related posts, 0 by default
paginationSinglePost = "true"

[[params.social]]
id = "github"
name="NikosAvg"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1


[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 3


[[menu.main]]
name = "Posts"
identifier = "posts"
url = "/posts/"
weight = 2

[markup.goldmark.renderer]
unsafe = true